[project]
name = "task-manager"
version = "0.1.0"
description = "A simple command-line task manager to organize daily tasks with due dates"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rich>=13.9.4",
]
